gift_participation:
  path: en_US/gift
  controller: App\Controller\GiftController::index

toto:
  path: /toto

odiseo_sylius_blog_admin:
    resource: "@OdiseoSyliusBlogPlugin/Resources/config/routing/admin.yml"
    prefix: /admin

odiseo_sylius_blog_shop:
    resource: "@OdiseoSyliusBlogPlugin/Resources/config/routing/shop.yml"
    prefix: /{_locale}/blog
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$