gift_participation:
  path: /us_US/gift
  controller: App\Controller\GiftController::index

lotery_chooser:
  path: /lotery
  controller: App\Controller\GiftController::lotery

toto:
  path: /toto

  

